GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

 {
    "text":"TeSting 2"
 }

###

DELETE http://localhost:3001/todo/delete/642c24d58c82ba5f5a23c0ec

###

GET  http://localhost:3001/todo/complete/6426c461c6a9a8952d9be9c4